import os

def main():

    def abort():
        print("Ungültige Eingabe. Bitte versuche es erneut.")
        input()
        main()

    kennzeichen = {
        'A':'Augsburg (Bay)',
        'AA': 'Aalen Ostalbkreis (BaWü)',
        'AB': 'Aschaffenburg (Bay)',
        'ABG': 'Altenburgs',
        'ABI': 'Landkreis Anhalt-Bitterfeld (SaAn)',
        'AC': 'Aachen (NrWe)',
        'AE': 'Vogtlandkreis (Sachs)',
        'AD': 'Privatfahrzeuge der amerikanischen Streitkräfte',
        'AF': 'Privatfahrzeuge der amerikanischen Streitkräfte',
        'AH': 'Ahaus im Kreis Borken (NrWe)',
        'AIB': 'Rosenheim',
        'AIC': 'Aichach-Friedberg (Bay)',
        'AK': 'Altenkirchen/Westerwald (RhPf)',
        'ALF': 'Hildesheim (NiSa)',
        'ALZ': 'Aschaffenburg (Bay)',
        'AM': 'Amberg (Bay)',
        'AN': 'Ansbach (Bay)',
        'ANA': 'Annaberg / Erzgebirgskreis (Sachs)',
        'ANG': 'Uckermark (Bran)',
        'ANK': 'Vorpommern / Greifswald (MeVo)',
        'AÖ': 'Altötting (Bay)',
        'AP': 'Weimarer-Land (Thür)',
        'APD': 'Weimarer-Land (Thür)',
        'ARN': 'Ilm-Kreis (Thür)',
        'ART': 'Kyffhäuserkreis (Thür)',
        'AS': 'Amberg-Sulzbach (Bay)',
        'ASL': 'Aschersleben-Staßfurter Salzlandkreis (SaAn)',
        'ASZ': 'Aue-Schwarzenberg / Erzbebirgskreis (Sachs)',
        'AT': 'Mecklenburgische Seenplatte (MeVo)',
        'AU': 'Erzgebirgskreis (Sachs)',
        'AUR': 'Aurich (NiSa)',
        'AW': 'Ahrweiler (RhPf)',
        'AZ': 'Alzey-Worms (RhPf)',
        'AZE': 'Anhalt-Zerbst / Bitterfeld (SaAn)',
        'B': 'Berlin (Hauptstadt und Regierungssitz der BRD)',
        'BA': 'Bamberg (Bay)',
        'BAD': 'Baden-Baden (BaWü)',
        'BAR': 'Barnim (Bran)',
        'BB': 'Böblingen (BaWü)',
        'BBG': 'Salzlandkreis (SaAn)',
        'BC': 'Biberach/Riss (BaWü)',
        'BCH': 'Neckar-Odenwald-Kreis (BaWü)',
        'BD 1': 'Deutscher Bundestag',
        'BD 3': 'Bundesrat',
        'BD 4': 'Bundesverfassungsbericht',
        'BD 5': 'Bundespräsidialamt',
        'BD 6': 'Bundeskanzleramt',
        'BD 7': 'Auswärtiges Amt',
        'BD 9': 'Bundesinnenministerium',
        'BD 10': 'Bundesjustizministerium',
        'BD 11': 'Bundesfinanzministerium',
        'BD 12': 'Bundesministerium für Wirtschaft und Technologie',
        'BD 13': 'Bundesministerium für Verkehr',
        'BD 16': 'Bundesfinanzverwaltung',
        'BD 18': 'Bundesverteidigungsministerium',
        'BD 19': 'Bundesministerium für Bildung und Forschung',
        'BD 20': 'Bundesministerium für Umwelt',
        'BD 21': 'Bundesministerium für Familie',
        'BD 22': 'Bundesgesundheitsministerium',
        'BD 26': 'Bundesministerium für wirtschaftliche Zusammenarbeit und Entwicklung',
        'BE': 'Warendorf (NrWe)',
        'BED': 'Landkreis Mittelsachsen (Sachs)',
        'BER': 'Barnim (Bran)',
        'BF': 'Steinfurt (NrWe)',
        'BGL': 'Berchtesgadener Land (Bay)',
        'BH': 'Rastatt (BaWü)',
        'BI': 'Bielefeld (NrWe)',
        'BID': 'Marburg-Biedenkopf (Hes)',
        'BIN': 'Mainz-Bingen (RhPf)',
        'BIR': 'Birkenfeld/Nahe und Idar-Oberstein (RhPf)',
        'BIT': 'Bitburg-Prüm (RhPf)',
        'BIW': 'Lankreis Bautzen (Sachs)',
        'BK': 'Rems-Murr-Kreis (BaWü)',
        'BKS': 'Bernkastel-Wittlich (RhPf)',
        'BL': 'Zollernalbkreis in Balingen (BaWü)',
        'BLB': 'Siegen-Wittgenstein (NrWe)',
        'BLK': 'Burgenlandkreis (SaAn)',
        'BM': 'Rhein-Erft-Kreis (NrWe)',
        'BN': 'Bonn (NrWe)',
        'BNA': 'Landkreis Leipzig (Sachs)',
        'BO': 'Bochum (NrWe)',
        'BÖ': 'Landkreis Börde (SaAn)',
        'BOH': 'Borken (NrWe)',
        'BOR': 'Borken (NrWe)',
        'BOT': 'Bottrop (NrWe)',
        'BRA': 'Wesermarsch in Brake (NiSa)',
        'BRB': 'Brandenburg (Bran)',
        'BRG': 'Jerichower Land (SaAn)',
        'BRK': 'Bad Brückenau (Bay)',
        'BRL': 'Goslar (NiSa)',
        'BRV': 'Rotenburg / Wümme (NiSa)',
        'BS': 'Braunschweig (NiSa)',
        'BT': 'Bayreuth (Bay)',
        'BTF': 'Landkreis Anhalt-Bitterfeld (SaAn)',
        'BÜD': 'Wetteraukreis (Hess)',
        'BÜR': 'Paderborn (NrWe)',
        'BÜS': 'Konstanz',
        'BÜZ': 'Landkreis Rostock (MeVo)',
        'BUL': 'Schwandorf',
        'BW': 'Bundes-Wasser- und Schiffahrtsverwaltung',
        'BWL': 'Baden-Württemberg Landesregierung und Landtag',
        'BYL': 'Bayern Landesregierung und Landtag',
        'BZ': 'Landkreis Bautzen (Sach)',
        'C': 'Chemnitz (Sachs)',
        'CA': 'Oberspreewald-Lausitz (Bran)',
        'CAS': 'Castrop-Rauxel',
        'CB': 'Cottbus (Bran)',
        'CE': 'Celle (NiSa)',
        'CHA': 'Cham/Oberpfalz (Bay)',
        'CLP': 'Cloppenburg (NiSa)',
        'CLZ': 'Goslar (NiSa)',
        'CO': 'Coburg (Bay)',
        'COC': 'Cochem-Zell/Mosel (RhPf)',
        'COE': 'Coesfeld/Westfalen (NrWe)',
        'CUX': 'Cuxhaven (NiSa)',
        'CW': 'Calw (BaWü)',
        'D': 'Düsseldorf (NrWe)',
        'DA': 'Darmstadt (Hess)',
        'DAH': 'Dachau (Bay)',
        'DAN': 'Lüchow-Dannenberg (NiSa)',
        'DAU': 'Daun (Eifel) (RhPf)',
        'DB': 'Deutsche Bundesbahn',
        'DBR': 'Bad Doberan (MeVo)',
        'DD': 'Dresden (Sachs)',
        'DE': 'Dessau (SaAn)',
        'DEG': 'Deggendorf (Bay)',
        'DEL': 'Delmenhorst (NiSa)',
        'DGF': 'Dingolfing-Landau (Bay)',
        'DH': 'Diepholz (NiSa)',
        'DI': 'Darmstadt-Dieburg (Hess)',
        'DIL': 'Lahn-Dill-Kreis (Hess)',
        'DIN': 'Wesel (NrWe)',
        'DKB': 'Landkreis Ansbach',
        'DL': 'Döbeln (Sachs)',
        'DLG': 'Dillingen/Donau (Bay)',
        'DM': 'Demmin (MeVo)',
        'DN': 'Düren (NrWe)',
        'DO': 'Dortmund (NrWe)',
        'DON': 'Donau-Ries in Donauwörth (Bay)',
        'DU': 'Duisburg (NrWe)',
        'DUD': 'Landkreis Göttingen',
        'DÜW': 'Bad Dürkheim (RhPf)',
        'DW': 'Dippoldiswalde / Sächsische Schweiz-Osterzgebirge (Sachs)',
        'DZ': 'Delitzsch / Landkreis Nordsachsen (Sachs)',
        'E': 'Essen (NrWe)',
        'EA': 'Eisenach (Thür)',
        'EB': 'Landkreis Nordsachen (Sachs)',
        'EBE': 'Ebersberg (Bay)',
        'EBN': 'Landkreis Haßberge',
        'EBS': 'Landkreis Forchheim',
        'ECK': 'Rendsburg-Eckernförde (SlHo)',
        'ED': 'Erding (Bay)',
        'EE': 'Elbe-Elster (Bran)',
        'EF': 'Erfurt (Thür)',
        'EG': 'Landkreis Rottal-Inn',
        'EH': 'Eisenhüttenstadt (Bran)',
        'EI': 'Eichstätt (Bay)',
        'EIC': 'Eichsfeld (Thür)',
        'EIL': 'Mansfeld-Südharz (SaAn)',
        'EIN': 'Northeim (NiSa)',
        'EIS': 'Saale-Holzland-Kreis (Thür)',
        'EL': 'Emsland in Meppen (NiSa)',
        'EM': 'Emmendingen (BaWü)',
        'EMD': 'Emden (NiSa)',
        'EMS': 'Rhein-Lahn-Kreis in Bad Ems (RhPf)',
        'EN': 'Ennepe-Ruhr-Kreis in Schwelm (NrWe)',
        'ER': 'Erlangen/Stadt (Bay)',
        'ERB': 'Odenwaldkreis in Erbach (Hess)',
        'ERH': 'Erlangen-Höchstadt (Bay)',
        'ERZ': 'Erzgebirgskreis (Sachs)',
        'ES': 'Esslingen/Neckar (BaWü)',
        'ESB': 'Kreis Neustadt a. d. Waldnaab',
        'ESW': 'Werra-Meissner-Kreis in Eschwege (Hess)',
        'EU': 'Euskirchen (NrWe)',
        'EW': 'Barnim (Bran)',
        'F': 'Frankfurt/Main (Hess)',
        'FB': 'Wetteraukreis in Friedberg (Hess)',
        'FD': 'Fulda (Hess)',
        'FDB': 'Landkreis Aichach-Friedberg (Bay)',
        'FDS': 'Freudenstadt (BaWü)',
        'FEU': 'Landkreis Ansbach',
        'FF': 'Frankfurt / Oder (Bran)',
        'FFB': 'Fürstenfeldbruck (Bay)',
        'FG': 'Freiberg / Landkreis Mittelsachsen (Sachs)',
        'FI': 'Elbe-Elster (Bran)',
        'FKB': 'Landkreis Waldeck-Frankenberg (Hess)',
        'FL': 'Flensburg (SlHo)',
        'FLO': 'Landkreis Mittelsachsen (Sachs)',
        'FN': 'Bodenseekreis in Friedrichshafen (BaWü)',
        'FO': 'Forchheim (Bay)',
        'FOR': 'Spree-Neiße (Bran)',
        'FR': 'Landkreis Breisgau-Hochschwarzwald',
        'FRG': 'Freyung-Grafenau (Bay)',
        'FRI': 'Jever in Friesland (NiSa)',
        'FRW': 'Märkisch-Oderland (Bran)',
        'FS': 'Freising (Bay)',
        'FT': 'Frankenthal/Pfalz (RhPf)',
        'FTL': 'Sächsische Schweiz-Osterzgebirge (Sachs)',
        'FÜ': 'Fürth (Bay)',
        'FÜS': 'Landkreis Ostallgäu',
        'G': 'Gera (Thür)',
        'GA': 'Gardelegen',
        'GAN': 'Landkreis Northeim',
        'GAP': 'Garmisch-Partenkirchen (Bay)',
        'GC': 'Landkreis Zwickau (Sachs)',
        'GD': 'Ostalbkreis (BaWü)',
        'GDB': 'Landkreis Nordwestmecklenburg (MeVo)',
        'GE': 'Gelsenkirchen (NrWe)',
        'GEL': 'Kleve (NrWe)',
        'GER': 'Germersheim (RhPf)',
        'GEO': 'Gerolzhofen (Bay)',
        'GF': 'Gifhorn (NiSa)',
        'GG': 'Gross-Gerau (Hess)',
        'GHA': 'Landkreis Leipzig (Sachs)',
        'GHC': 'Wittenberg (SaAn)',
        'GI': 'Giessen (Hess)',
        'GK': 'Kreis Heinsberg',
        'GL': 'Rheinisch-Bergischer Kreis in Bergisch Gladbach (NrWe)',
        'GLA': 'Gladbeck',
        'GM': 'Oberbergischer Kreis in Gummersbach (NrWe)',
        'GMN': 'Landkreis Vorpommern-Rügen (MeVo)',
        'GN': 'Main-Kinzig-Kreis (Hess)',
        'GNT': 'Jerichower Land (SaAn)',
        'GÖ': 'Göttingen (NiSa)',
        'GOA': 'Rhein-Hunsrück-Kreis (RhPf)',
        'GOH': 'Rhein-Lahn-Kreis',
        'GP': 'Göppingen (BaWü)',
        'GR': 'Görlitz (Sachs)',
        'GRA': 'Landkreis Freyung-Grafenau (Bay)',
        'GRH': 'Landkreis Meißen (Sachs)',
        'GRI': 'Landkreis Rottal-Inn',
        'GRM': 'Landkreis Leipzig',
        'GRZ': 'Greiz (Thür)',
        'GS': 'Goslar (NiSa)',
        'GT': 'Gütersloh (NrWe)',
        'GTH': 'Gotha (Thür)',
        'GUB': 'Spree-Neiße (Bran)',
        'GUN': 'Landkreis Weißenburg-Gunzenhausen (Bay)',
        'GÜ': 'Landkreis Rostock',
        'GVM': 'Landkreis Nordwestmecklenburg (MeVo)',
        'GW': 'Landkreis Vorpommern-Greifswald (MeVo)',
        'GZ': 'Günzburg (Bay)',
        'H': 'Hannover (NiSa)',
        'HA': 'Hagen/Westfalen (NrWe)',
        'HAB': 'Landkreis Bad Kissingen',
        'HAL': 'Halle/Saale (SaAn)',
        'HAM': 'Hamm/Westfalen (NrWe)',
        'HAS': 'Hassberge in Hassfurt (Bay)',
        'HB': 'Freie Hansestadt Bremen und Bremerhaven (Bre)',
        'HBN': 'Hildburghausen (Thür)',
        'HBS': 'Halberstadt / Landkreis Harz (SaAn)',
        'HC': 'Landkreis Mittelsachsen (Sachs)',
        'HCH': 'Zollernalbkreis (BaWü)',
        'HD': 'Rhein-Neckar-Kreis und Heidelberg (BaWü)',
        'HDH': 'Heidenheim/Brenz (BaWü)',
        'HDL': 'Landkreis Börde (SaAn)',
        'HE': 'Helmstedt (NiSa)',
        'HEB': 'Landkreis Nürnberger Land',
        'HEF': 'Bad Hersfeld-Rotenburg (Hess)',
        'HEI': 'Heide in Dithmarschen/Holstein (SlHo)',
        'HER': 'Herne (NrWe)',
        'HET': 'Mansfeld Südharz (SaAn)',
        'HF': 'Herford in Kirchlengern (NrWe)',
        'HG': 'Hochtaunuskreis in Bad Homburg v.d.H. (Hess)',
        'HGN': 'Landkreis Ludwigslust-Parchim (MeVo)',
        'HGW': 'Hansestadt Greifswald (MeVo)',
        'HH': 'Freie Hansestadt Hamburg (Hbg)',
        'HHM': 'Burgenlandkreis (SaAn)',
        'HI': 'Hildesheim (NiSa)',
        'HIG': 'Eichsfeld (Thür)',
        'HIP': 'Landkreis Roth',
        'HK': 'Privatfahrzeuge der amerikanischen Streitkräfte',
        'HK': 'Heidekreis (NiSa)',
        'HL': 'Hansestadt Lübeck (SlHo)',
        'HM': 'Hameln-Pyrmont (NiSa)',
        'HMÜ': 'Landkreis Göttingen (NiSa)',
        'HN': 'Heilbronn/Neckar (BaWü)',
        'HO': 'Hof (Bay)',
        'HOG': 'Kassel (Kreis) (Hess)',
        'HOH': 'Landkreis Haßberge (Bay)',
        'HOL': 'Holzminden (NiSa)',
        'HOM': 'Saar-Pfalz-Kreis in Homburg/Saar (Saar)',
        'HOR': 'Landkreis Horb',
        'HOT': 'Landkreis Zwickau (Sachs)',
        'HÖS': 'Landkreis Erlangen Höchstadt (Bay)',
        'HP': 'Bergstrasse in Heppenheim (Hess)',
        'HR': 'Schwalm-Eder-Kreis in Homberg (Hess)',
        'HRO': 'Hansestadt Rostock (MeVo)',
        'HS': 'Heinsberg (NrWe)',
        'HSK': 'Hochsauerlandkreis in Meschede (NrWe)',
        'HST': 'Hansestadt Stralsund (MeVo)',
        'HU': 'Main-Kinzing-Kreis / Hanau (Hess)',
        'HV': 'Landkreis Stendal',
        'HVL': 'Havelland (Bran)',
        'HWI': 'Hansestadt Wismar (MeVo)',
        'HX': 'Höxter (NrWe)',
        'HY': 'Hoyerswerda / Landkreis Bautzen (Sachs)',
        'HZ': 'Landkreis Harz (SaAn)',
        'IGB': 'St. Ingbert (Saar)',
        'IK': 'Ilm-Kreis (Thür)',
        'IL': 'Ilmenau (Thür)',
        'ILL': 'Landkreis Neu-Ulm',
        'IN': 'Ingolstadt/Donau (Bay)',
        'IZ': 'Kreis Steinburg',
        'J': 'Jena (Thür)',
        'JE': 'Landkreis Wittenberg',
        'JL': 'Jerichower Land (SaAn)',
        'JÜL': 'Kreis Düren',
        'K': 'Köln (NrWe)',
        'KA': 'Karlsruhe (BaWü)',
        'KB': 'Waldeck-Frankenberg in Korbach (Hess)',
        'KC': 'Kronach (Bay)',
        'KE': 'Kempten/Allgäu (Bay)',
        'KEH': 'Kelheim (Bay)',
        'KEL': 'Ortenauskreis (BaWü)',
        'KEM': 'Tirschenreuth',
        'KF': 'Kaufbeuren (Bay)',
        'KG': 'Bad Kissingen (Bay)',
        'KH': 'Bad Kreuznach (RhPf)',
        'KI': 'Kiel (SlHo)',
        'KIB': 'Donnersberg-Kreis in Kirchheimbolanden (RhPf)',
        'KK': 'Viersen (NrWe)',
        'KL': 'Kaiserslautern',
        'KLE': 'Kleve (NrWe)',
        'KLZ': 'Altmarkkreis-Salzwedel (SaAn)',
        'KM': 'Landkreis Bautzen (Sachs)',
        'KN': 'Konstanz (BaWü)',
        'KO': 'Koblenz (RhPf)',
        'KÖN': 'Bad Königshofen im Grabfeld - Rhön-Grabfeld (Bay)',
        'KÖT': 'Köthen / Anhalt-Bitterfeld (SaAn)',
        'KÖZ': 'Landkreis Cham - Kötzting (Bay)',
        'KR': 'Krefeld (NrWe)',
        'KRU': 'Günzburg (Bay)',
        'KS': 'Kassel',
        'KT': 'Kitzingen (Bay)',
        'KU': 'Kulmbach (Bay)',
        'KÜN': 'Hohenlohe-Kreis (BaWü)',
        'KUS': 'Kusel (RhPf)',
        'KY': 'Ostprignitz-Ruppin (Bran)',
        'KYF': 'Kyffhäuserkreis (Thür)',
        'L': 'Leipzig',
        'LA': 'Landshut',
        'LAU': 'Lauf / Pegnitz - Nürnberger Land (Bay)',
        'LB': 'Ludwigsburg (BaWü)',
        'LBS': 'Saale-Orla-Kreis (Thür)',
        'LBZ': 'Landkreis Ludwigslust-Parchim (MeVo)',
        'LD': 'Landau i. d. Pfalz (RhPf)',
        'LDK': 'Lahn-Dill-Kreis (Hess)',
        'LDS': 'Dahme-Spreewald (Bran)',
        'LEO': 'Böblingen (BaWü)',
        'LER': 'Leer (NiSa)',
        'LEV': 'Leverkusen (NrWe)',
        'LG': 'Lüneburg (NiSa)',
        'LH': 'Coesfeld (NrWe)',
        'LI': 'Lindau / Bodensee (Bay)',
        'LIB': 'Elbe-Elster (Bran)',
        'LIF': 'Lichtenfels (Bay)',
        'LIP': 'Lippe in Detmold (NrWe)',
        'LL': 'Landsberg / Lech (Bay)',
        'LM': 'Limburg-Weilburg / Lahn (Hess)',
        'LÖ': 'Lörrach (BaWü)',
        'LÖB': 'Landkreis Görlitz (Sachs)',
        'LOS': 'Oder-Spree (Bran)',
        'LP': 'Soest (NrWe)',
        'LR': 'Ortenauskreis (BaWü)',
        'LRO': 'Landkreis Rostock (MeVo)',
        'LSA': 'Sachsen-Anhalt Landesregierung und Landtag (SaAn)',
        'LSZ': 'Unstrut-Hainich-Kreis (Thür)',
        'LU': 'Ludwigshafen (RhPf)',
        'LUN': 'Unna (NrWe)',
        'LUP': 'Ludwigslust-Parchim (MeVo)',
        'LWL': 'Landkreis Ludwigslust-Parchim (MeVo)',
        'M': 'München',
        'MA': 'Mannheim (BaWü)',
        'MAB': 'Erzgebirgskreis (Sachs)',
        'MAI': 'Kelheim',
        'MAK': 'Wunsiedel i. Fichtelgebirge (Bay)',
        'MAL': 'Landshut (Bay)',
        'MB': 'Miesbach (Bay)',
        'MC': 'Mecklenburgische Seenplatte (MeVo)',
        'MD': 'Magdeburg (SaAn)',
        'ME': 'Mettmann (NrWe)',
        'MEI': 'Meissen (Sachs)',
        'MEK': 'Mittl. Erzgebirgskreis (Sachs)',
        'MER': 'Saalekreis (SaAn)',
        'MET': 'Rhön-Grabfeld (Bay)',
        'MG': 'Mönchengladbach (NrWe)',
        'MGH': 'Main-Tauber-Kreis (BaWü)',
        'MGN': 'Schmalkalden-Meiningen (Thür)',
        'MH': 'Mülheim an der Ruhr (NrWe)',
        'MHL': 'Unstrut-Hainich-Kreis (Thür)',
        'MI': 'Minden-Lübbecke / Westfalen (NrWe)',
        'MIL': 'Miltenberg (Bay)',
        'MKK': 'Main-Kinzig-Kreis (Hessen)',
        'ML': 'Mansfeld-Südharz (SaAn)',
        'MK': 'Märkischer Kreis in Lüdenscheid (NrWe)',
        'MM': 'Memmingen (Bay)',
        'MN': 'Unterallgäu in Mindelheim (Bay)',
        'MO': 'Wesel (NrWe)',
        'MOD': 'Ostallgäu (Bay)',
        'MOL': 'Märkisch-Oderland (Bran)',
        'MON': 'Aachen (NrWe)',
        'MOS': 'Neckar-Odenwald-Kreis in Mosbach (BaWü)',
        'MQ': 'Merseburg-Querfurt / Saalekreis (SaAn)',
        'MR': 'Marburg-Biedenkopf an der Lahn (Hessen)',
        'MS': 'Münster / Westfalen (NrWe)',
        'MSE': 'Mecklenburgische Seenplatte (MeVo)',
        'MSH': 'Mansfeld-Südharz-Kreis (SaAn)',
        'MSP': 'Main-Spessart-Kreis in Karlstadt (Bay)',
        'MST': 'Mecklenburg-Strelitz (MeVo)',
        'MTK': 'Main-Taunus-Kreis in Hofheim (Hess)',
        'MTL': 'Muldentalkreis',
        'MÜB': 'Bayreuth',
        'MÜ': 'Mühldorf am Inn (Bay)',
        'MÜR': 'Müritz',
        'MW': 'Mittweida',
        'MY': 'Mayen-Koblenz (RhPf)',
        'MYK': 'Mayen-Koblenz (RhPf)',
        'MZ': 'Mainz-Bingen und Mainz (RhPf)',
        'MZG': 'Merzig-Wadern (Saar)',
        'N': 'Nürnberg',
        'NAB': 'Amberg-Sulzbach',
        'NAI': 'Naila',
        'NB': 'Neubrandenburg (MeVo)',
        'ND': 'Neuburg-Schrobenhausen an der Donau (Bay)',
        'NDH': 'Nordhausen (Thür)',
        'NE': 'Neuss',
        'NEA': 'Neustadt-Bad Windsheim an der Aisch (Bay)',
        'NEB': 'Burgenlandkreis (SaAn)',
        'NEC': 'Neustadt bei Coburg',
        'NEN': 'Landkreis Schwandorf',
        'NES': 'Rhön-Grabfeld in Bad Neustadt an der Saale (Bay)',
        'NEW': 'Neustadt an der Waldnaab (Bay)',
        'NF': 'Nordfriesland in Husum (SlHo)',
        'NH': 'Sonneberg (Thür)',
        'NI': 'Nienburg an der Weser (NiSa)',
        'NK': 'Neunkirchen an der Saar (Saar)',
        'NM': 'Neumarkt / Oberpfalz (Bay)',
        'NMB': 'Burgenlandkreis (SaAn)',
        'NMS': 'Neumünster (SlHo)',
        'NOH': 'Grafschaft Bentheim in Nordhorn (NiSa)',
        'NOL': 'Niederschlesische Oberlausitz',
        'NOM': 'Northeim (NiSa)',
        'NOR': 'Aurich (NiSa)',
        'NÖ': 'Donau-Ries',
        'NP': 'Ostprigniz-Ruppin (Bran)',
        'NR': 'Neuwied am Rhein',
        'NT': 'Esslingen (BaWü)',
        'NU': 'Neu-Ulm (Bay)',
        'NVP': 'Nordvorpommern',
        'NW': 'Neustadt an der Weinstrasse (RhPf)',
        'NWM': 'Landkreis Nordwestmecklenburg (MeVo)',
        'NY': 'Landkreis Görlitz (Sachs)',
        'NZ': 'Meklenburgische Seenplatte (MeVo)',
        'OA': 'Oberallgäu in Sonthofen (Bay)',
        'OAL': 'Ostallgäu in Marktoberdorf (Bay)',
        'OB': 'Oberhausen/Rheinland (NrWe)',
        'OBG': 'Stendal (SaAn)',
        'OC': 'Landkreis Börde (SaAn)',
        'OCH': 'Ochsenfurt (Bay)',
        'OD': 'Stormarn in Bad Oldesloe (SlHo)',
        'OE': 'Olpe (NrWe)',
        'OF': 'Offenbach/Main (Hess)',
        'OG': 'Ortenaukreis in Offenburg (BaWü)',
        'OH': 'Ostholstein in Eutin (SlHo)',
        'OHA': 'Osterode/Harz (NiSa)',
        'OHV': 'Oberhavel (Bran)',
        'OHZ': 'Osterholz-Scharmbeck (NiSa)',
        'OK': 'Ohrekreis (SaAn)',
        'OL': 'Oldenburg (NiSa)',
        'OPR': 'Ostprignitz-Ruppin (Bran)',
        'OS': 'Osnabrück (NiSa)',
        'OSL': 'Oberspreewald-Lausitz (Bran)',
        'OVL': 'Vogtlandkreis (Sachs)',
        'OVP': 'Ostvorpommern (MeVo)',
        'P': 'Potsdam (Bran)',
        'PA': 'Passau (Bay)',
        'PAF': 'Pfaffenhofen/Ilm (Bay)',
        'PAN': 'Rottal-Inn in Pfarrkirchen (Bay)',
        'PB': 'Paderborn (NrWe)',
        'PCH': 'Parchim (MeVo)',
        'PE': 'Peine (NiSa)',
        'PF': 'Enzkreis und Pforzheim (BaWü)',
        'PI': 'Pinneberg (SlHo)',
        'PIR': 'Pirna (Sachs)',
        'PL': 'Plauen (Sachs)',
        'PLÖ': 'Plön/Holstein (SlHo)',
        'PM': 'Potsdam-Mittelmark (Bran)',
        'PN': 'Saale-Orla-Kreis (Thür)',
        'PR': 'Prignitz (Bran)',
        'PRÜ': 'Bitburg-Prüm (RhPf)',
        'PS': 'Pirmasens/Südwestpfals (RhPf)',
        'PW': 'Landkreis Vorpommern-Greifswald (MeVo)',
        'QFT': 'Saalekreis (SaAn)',
        'QLB': 'Quedlinburg / Landkreis Harz (SaAn)',
        'R': 'Regensburg (Bay)',
        'RA': 'Rastatt (BaWü)',
        'RC': 'Vogtlandkreis (Sachs)',
        'RD': 'Rendsburg-Eckernfoerde (SlHo)',
        'RDG': 'Landkreis Vorpommern-Rügen (MeVo)',
        'RE': 'Recklinghausen in Marl (NrWe)',
        'REG': 'Regen (Bayr. Wald) (Bay)',
        'RG': 'Riesa-Großenhain / Landkreis Meißen (Sachs)',
        'RH': 'Roth/Rednitz (Bay)',
        'RI': 'Schaumburg (NiSa)',
        'RIE': 'Landkreis Meißen (Sachs)',
        'RL': 'Landkreis Mittelsachsen (Sachs)',
        'RM': 'Mecklenburgische Seenplatte (MeVo)',
        'RO': 'Rosenheim (Bay)',
        'ROW': 'Rotenburg/Wümme (NiSa)',
        'RP': 'Rhein-Pfalz-Kreis (RhPf)',
        'RS': 'Remscheid (NrWe)',
        'RSL': 'Dessau-Roßlau (SaAn)',
        'RT': 'Reutlingen (BaWü)',
        'RÜD': 'Rheingau-Taunus-Kreis in Rüdesheim (Hess)',
        'RÜG': 'Rügen (MeVo)',
        'RV': 'Ravensburg (BaWü)',
        'RW': 'Rottweil (BaWü)',
        'RZ': 'Herzogtum Lauenburg in Ratzeburg (SlHo)',
        'S': 'Stuttgart (BaWü)',
        'SAB': 'Landkreis Trier-Saarburg (RhPf)',
        'SAD': 'Schwandorf (Bay)',
        'SAN': 'Hof',
        'SAW': 'Altmarkkreis-Salzwedel (SaAn)',
        'SB': 'Saarbrücken (Saar)',
        'SBG': 'Vorprommern-Greifswald (MeVo)',
        'SBK': 'Schönebeck/Elbe (SaAn)',
        'SC': 'Schwabach (Bay)',
        'SCZ': 'Saale-Orla-Kreis (Thür)',
        'SDH': 'Kyffhäuserkreis (Thür)',
        'SDL': 'Stendal (SaAn)',
        'SDT': 'Uckermark (Bran)',
        'SE': 'Bad Segeberg (SlHo)',
        'SEB': 'Sächsische Schweiz-Osterzgebirge',
        'SEE': 'Märkisch Oderland (Bran)',
        'SEF': 'Neustadt an der Aisch',
        'SFA': 'Soltau-Fallingbostel (NiSa)',
        'SFB': 'Oberspreewald-Lausitz (Bran)',
        'SFT': 'Salzlandkreis (SaAn)',
        'SG': 'Solingen (NrWe)',
        'SGH': 'Landkreis Mansfeld-Südharz (SaAn)',
        'SHA': 'Schwäbisch Hall (BaWü)',
        'SHG': 'Schaumburg in Stadthagen (NiSa)',
        'SHK': 'Saale-Holzlandkreis (Thür)',
        'SHL': 'Suhl (Thür)',
        'SI': 'Siegen-Wittgenstein (NrWe)',
        'SIG': 'Sigmaringen (BaWü)',
        'SIM': 'Rhein-Hunsrück-Kreis in Simmern (RhPf)',
        'SK': 'Saalkreis in Halle (SaAn)',
        'SL': 'Schleswig-Flensburg (SlHo)',
        'SLE': 'Kreis Euskirchen',
        'SLF': 'Saalfeld-Rudolstadt (Thür)',
        'SLK': 'Salzlandkreis (SaAn)',
        'SLN': 'Altenburger Land (Thür)',
        'SLS': 'Saarlouis (Saar)',
        'SLÜ': 'Main-Kinzing-Kreis (Hess)',
        'SLZ': 'Wartburgkreis (Thür)',
        'SM': 'Schmalkalden-Meiningen (Thür)',
        'SN': 'Schwerin',
        'SO': 'Soest (NrWe)',
        'SOB': 'Neuburg-Schrobenhausen (Bay)',
        'SOG': 'Weilheim-Schongau (Bay)',
        'SÖM': 'Sömmerda (Thür)',
        'SOK': 'Saale-Orla-Kreis (Thür)',
        'SON': 'Sonneberg (Thür)',
        'SP': 'Speyer (RhPf)',
        'SPB': 'Spree-Neiße (Bran)',
        'SPN': 'Spree-Neisse (Bran)',
        'SR': 'Straubing-Bogen',
        'SRB': 'Märkisch Oderland (Bran)',
        'SRO': 'Saale-Holzland-Kreis (Thür)',
        'ST': 'Steinfurt (NrWe)',
        'STA': 'Starnberg (Bay)',
        'STB': 'Ludwigslust-Parchim (MeVo)',
        'STD': 'Stade (NiSa)',
        'STE': 'Lichtenfels (Bay)',
        'STL': 'Stollberg',
        'SU': 'Rhein-Sieg-Kreis in Siegburg (NrWe)',
        'SUL': 'Amberg-Sulzbach (Bay)',
        'SÜW': 'Südl. Weinstrasse in Landau (RhPf)',
        'SW': 'Schweinfurt',
        'SWA': 'Rheingau-Taunus-Kreis (Hess)',
        'SZ': 'Salzgitter (NiSa)',
        'SZB': 'Erzgebirgskreis (Sachs)',
        'TBB': 'Main-Tauber-Kreis in Tauberbischofsheim (BaWü)',
        'TDO': 'Torgau Delitzsch - Oschatz',
        'TE': 'Steinfurt (NrWe)',
        'TET': 'Teterow',
        'TF': 'Teltow-Fläming (Bran)',
        'TG': 'Landkreis Nordsachsen (Sachs)',
        'TIR': 'Tirschenreuth (Bay)',
        'TO': 'Landkreis Nordsachsen (Sachs)',
        'TÖL': 'Bad Tölz-Wolfratshausen (Bay)',
        'TP': 'Uckermark (Bran)',
        'TR': 'Trier-Saarburg (RhPf)',
        'TS': 'Traunstein (Bay)',
        'TÜ': 'Tübingen (BaWü)',
        'TUT': 'Tuttlingen (BaWü)',
        'UE': 'Uelzen (NiSa)',
        'UEM': 'Landkreis Vorpommern-Greifswald (MeVo)',
        'UER': 'Landkreis Vorpommern-Greifswald (MeVo)',
        'UFF': 'Neustadt a. d. Aisch-Bad Windsheim (Bay)',
        'UH': 'Unstrut-Hainich-Kreis (Thür)',
        'UL': 'Alb-Donau-Kreis und Ulm (BaWü)',
        'UM': 'Uckermark (Bran)',
        'UN': 'Unna/Westfalen (NrWe)',
        'USI': 'Hochtaunuskreis (Hess)',
        'V': 'Vogtlandkreis (Sachs)',
        'VAI': 'Ludwigsburg (BaWü)',
        'VB': 'Vogelsbergkreis in Lauterbach (Hess)',
        'VEC': 'Vechta (NiSa)',
        'VER': 'Verden/Aller (NiSa)',
        'VG': 'Landkreis Vorpommern-Greifswald (MeVo)',
        'VIB': 'Landshut',
        'VIE': 'Viersen (NrWe)',
        'VK': 'Völklingen (Saar)',
        'VOH': 'Neustadt a. d. Waldnaab (Bay)',
        'VR': 'Landkreis Vorpommern-Rügen (MeVo)',
        'VS': 'Schwarzwald-Baar-Kreis (BaWü)',
        'W': 'Wuppertal (NrWe)',
        'WA': 'Waldeck-Frankenberg (Hess)',
        'WAF': 'Warendorf (NrWe)',
        'WAK': 'Wartburgkreis (Thür)',
        'WAN': 'Herne (NrWe)',
        'WAT': 'Bochum (NrWe)',
        'WB': 'Wittenberg (SaAn)',
        'WBS': 'Eichsfeld (Thür)',
        'WDA': 'Landkreis Zwickau (Sachs)',
        'WE': 'Weimar (Thür)',
        'WEL': 'Limburg-Weilburg (Hess)',
        'WEN': 'Weiden in der Oberpfalz (Bay)',
        'WER': 'Dillingen a. d. Donau (Bay)',
        'WES': 'Wesel (NrWe)',
        'WF': 'Wolfenbüttel (NiSa)',
        'WHV': 'Wilhelmshaven (NiSa)',
        'WI': 'Wiesbaden (Hess)',
        'WIL': 'Bernkastel-Wittlich/Mosel (RhPf)',
        'WIS': 'Landkreis Nordwestmecklenburg (MeVo)',
        'WIT': 'Ennepe-Ruhr-Kreis (NrWe)',
        'WK': 'Ostprigniz-Ruppin (Bran)',
        'WIZ': 'Werra-Meißner-Kreis (Hess)',
        'WL': 'Harburg in Winsen/Luhe (NiSa)',
        'WLG': 'Landkreis Vorpommern-Greifswald (MeVo)',
        'WM': 'Weilheim-Schongau/Oberbayern (Bay) und ereinzelt in Bremerhaven für Landkreis Wesermünde',
        'WMS': 'Landkreis Börde (SaAn)',
        'WN': 'Rems-Murr-Kreis in Waiblingen (BaWü)',
        'WND': 'St. Wendel (Saar)',
        'WO': 'Worms (RhPf)',
        'WOB': 'Wolfsburg (NiSa)',
        'WOH': 'Landkreis Kassel (Hess)',
        'WOL': 'Ortenaukreis (BaWü)',
        'WOR': 'Bad Tölz-Wolfratshausen',
        'WOS': 'Freyung-Grafenau (Bay)',
        'WR': 'Wernigerode',
        'WRN': 'Mecklenburgische Seenplatte (MeVo)',
        'WS': 'Rosenheim (Bay)',
        'WSF': 'Weißenfels',
        'WST': 'Ammerland in Westerstede (NiSa)',
        'WSW': 'Landkreis Görlitz (Sachs)',
        'WT': 'Waldshut-Tiengen (BaWü)',
        'WTM': 'Wittmund (NiSa)',
        'WÜ': 'Würzburg (Stadt und Kreis) (Bay)',
        'WUG': 'Weissenburg-Gunzenhausen (Bay)',
        'WUN': 'Wunsiedel (Bay)',
        'WÜM': 'Cham (Bay)',
        'WUR': 'Wurzen',
        'WW': 'Westerwald in Montabaur (RhPf)',
        'WZ': 'Dill-Kreis (Hess)',
        'WZL': 'Landkreis Börde (SaAn)',
        'X': 'Bundeswehr für NATO-Hauptquartiere',
        'Y': 'Bundeswehr',
        'Z': 'Landkreis Zwickau (Sachs)',
        'ZE': 'Anhalt-Bitterfeld (SaAn)',
        'ZEL': 'Cochem-Zell (RhPf)',
        'ZI': 'Landkreis Görlitz (Sachs)',
        'ZP': 'Erzgebirgskreis (Sachs)',
        'ZR': 'Greiz (SaAn)',
        'ZW': 'Zweibrücken (RhPf)',
        'ZZ': 'Burgenlandkreis (SaAn)'
    }

    os.system("cls")
    print("                                      KFZ-Kennzeichen-Erkenner in DE by Inkognito")
    eing = str(input("\n\nKennzeichen: "))

    try:
        print(kennzeichen[eing.upper()])
        input()
        main()
    except:
        abort()


main()